# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f3783747164c8b76f5b7e57ee6754166a2179306ec389d7a644a413425e7a75beec0fe4178668d3e5516daf999c2934c2fd746fa9842113b7576f07e25927c

test:
  secret_key_base: 227f2a71f7711426197f758afc972d92663c3eb3d6cc3c1f19956a0ea837bbc3e35654f6bc90e81e9c9797ed6bf88fd402f6d801dc3c608b1812c5a4cb226260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
